[build]
command = "npm run build"
publish = "build"

[context.production.environment]
REACT_APP_API_ENDPOINT = "https://x2f6t6erka.execute-api.ap-northeast-2.amazonaws.com/test"
REACT_APP_API_KEY = "JnEzsX46YX7vgbU1HVPZM6rZvhKXj7Gz7xpGHrdO"
REACT_APP_API_USER = "Jeongdaeji"